[build]
  command = "python3 -m pip install --user -r requirements.txt && export PATH=\"$HOME/.local/bin:$PATH\" && npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"





